Expand user unit tests
Devoxx4Kids-NPO/littil-backend pull request #89
Opened 2022-09-29 14:01 UTC by roelandkulk

2022-09-30 09:49 UTC, pschildkamp requested changes
Minor non-trivial comments, but good to do anyway ;). Thanks for your contribution.

2022-09-30 09:49 UTC, pschildkamp commented on src/test/java/org/littil/api/user/api/UserResourceTest.java
> +        user.setEmailAddress(RandomStringUtils.randomAlphabetic(10) + "@adres.nl");
This goes for multiple tests

2022-09-30 10:17 UTC, roelandkulk commented on src/test/java/org/littil/api/user/api/UserResourceTest.java
> +        user.setEmailAddress(RandomStringUtils.randomAlphabetic(10) + "@adres.nl");
done

2022-09-30 10:17 UTC, roelandkulk commented on src/main/java/org/littil/api/exception/EntityAlreadyExistsExceptionMapper.java
> +@Slf4j
done

2022-10-03 08:15 UTC, pschildkamp requested changes

2022-10-03 09:02 UTC, merged